# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Cayll
email: dcayll@utexas.edu
description: >- # this means to ignore newlines until "baseurl:"
  I'm currently a PhD student at the Univeristy of Texas at Austin in the
  Nanoscale Design and Manufacturing lab. I'm also working part time as an R&D
  Engineer at GraphAudio inc, a small start-up based in Austin. In my spare time
  I enjoy being outdoors, riding motorcycles, lifting weights, practicing macro
  and astro photography, and learning about macro economics and monetary policy.
  This website is for organizing my random thoughts and hobbies, and hopefully
  these things may be helpful to others.
instagram_username: dcayll
twitter_username: dcayll
github_username: dcayll
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "David Cayll"
  avatar : "/assets/images/DSC04797.JPG"
  bio    : "Thinking, learning, and writing in real time. Mostly for me, but take what you will"
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/david-cayll/"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dcayll"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/dcayll"

footer:
  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/dcayll95"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/david-cayll/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dcayll"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/dcayll"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # _photography
  - scope:
      path: "_photography"
      type: photography
    values:
      layout: single
      author_profile: true

  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: single
      author_profile: true

  # _finances
  - scope:
      path: "_finances"
      type: finaces
    values:
      layout: single
      author_profile: true

  # _fitness
  - scope:
      path: "_fitness"
      type: fitness
    values:
      layout: single
      author_profile: true

  # _engineering
  - scope:
      path: "_engineering"
      type: engineering
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
